[package]
name = "evo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
image = "0.23.14"
itertools = "0.10.1"
num = "0.4.0"
num_cpus = "1.13.0"
